name: Build and Test

on:
  - pull_request
  - push

jobs:
  build-and-test:
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        ocaml-version:
          - 4.12.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - name: Install dependencies
        run: opam install dune ppx_deriving ounit2 menhir

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.opam
          key: deps-${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('dune-project', '**/dune') }}

      - name: Build
        run: opam exec -- dune build && cp _build/default/bin/austral.exe austral

      - name: Run OCaml tests
        run: opam exec -- dune runtest

      - name: Run test script
        run: ./run-tests.sh

      - name: Upload compiler binary
        uses: actions/upload-artifact@v2
        with:
          name: austral-${{ runner.os }}-bin
          path: austral
          # This is for making releases without building manually on each
          # operating system. So we don't need the full 90 day retention
          # period.
          retention-days: 1
