name: Build and Test

on:
  - push

jobs:
  build-and-test:
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        ocaml-version:
          - 4.12.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # See: https://github.com/ocaml/setup-ocaml/issues/529#issuecomment-1142547616
      - name: Hack Git CRLF for ocaml/setup-ocaml issue #529
        if: ${{ startsWith(matrix.os, 'windows-') }}
        run: |
          & "C:\Program Files\Git\bin\git.exe" config --system core.autocrlf input

      - name: Set up OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}

      - name: Install a specific version of ppxlib
        run: opam install ppxlib.0.25.0

      - name: Install dependencies
        run: opam install dune ppx_deriving ounit2 menhir yojson ppx_deriving_yojson

      - name: Build
        run: make

      - name: Install
        run: sudo make install
        if: runner.os == 'Linux'

      - name: Run OCaml tests
        run: opam exec -- dune runtest
        if: runner.os == 'Linux'

      - name: Run example programs
        run: ./run-tests.sh
        if: runner.os == 'Linux'

      - name: Run test script
        run: python3 test-programs/runner.py
        if: runner.os == 'Linux'

      - name: Upload compiler binary
        uses: actions/upload-artifact@v2
        with:
          name: austral-${{ runner.os }}-bin
          path: austral
          # This is for making releases without building manually on each
          # operating system. So we don't need the full 90 day retention
          # period.
          retention-days: 1
