name: Build and Test

on:
  - pull_request
  - push

jobs:
  build-and-test:
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
        ocaml-version:
          - 4.12.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - name: Install dependencies
        run: opam install dune ppx_deriving ounit2 menhir

      - name: Build
        run: opam exec -- dune build

      - name: Run OCaml tests
        run: opam exec -- dune runtest

      - name: Run test script
        run: ./run-tests.sh
