name: Build and Test

on:
  - push

jobs:
  build-and-test-linux:
    strategy:
      fail-fast: true

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install opam
        run: sudo apt-get install -y opam

      - name: Initialize opam
        run: opam init

      - name: Install dependencies
        run: opam install -y dune ppx_deriving ounit2 menhir

      - name: Build
        run: make

      - name: Install
        run: sudo make install

      - name: Run OCaml tests
        run: opam exec -- dune runtest

      - name: Run test script
        run: ./run-tests.sh

      - name: Upload compiler binary
        uses: actions/upload-artifact@v2
        with:
          name: austral-${{ runner.os }}-bin
          path: austral
          # This is for making releases without building manually on each
          # operating system. So we don't need the full 90 day retention
          # period.
          retention-days: 1

  build-and-test:
    strategy:
      fail-fast: true
      matrix:
        os:
          - macos-latest
          - windows-latest
        ocaml-version:
          - 4.12.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}

      - name: Install dependencies
        run: opam install dune ppx_deriving ounit2 menhir

      - name: Build
        run: make

      - name: Upload compiler binary
        uses: actions/upload-artifact@v2
        with:
          name: austral-${{ runner.os }}-bin
          path: austral
          # This is for making releases without building manually on each
          # operating system. So we don't need the full 90 day retention
          # period.
          retention-days: 1
